// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYFcYx25_R_NH6lZUr8vaANp7HiBoj1TI',
    appId: '1:31700413083:web:02851832332ce323aa343e',
    messagingSenderId: '31700413083',
    projectId: 'leap-f50f3',
    authDomain: 'leap-f50f3.firebaseapp.com',
    storageBucket: 'leap-f50f3.appspot.com',
    measurementId: 'G-B81WQ0QTFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr0ennNwCjAiU2dNRMBcZ_spcEXJ1qu_U',
    appId: '1:31700413083:android:5877c615dc208ba5aa343e',
    messagingSenderId: '31700413083',
    projectId: 'leap-f50f3',
    storageBucket: 'leap-f50f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt0fWYENz-TfXifceRsdd2e05a7Tq0kr0',
    appId: '1:31700413083:ios:fb5f52126aa8f0e7aa343e',
    messagingSenderId: '31700413083',
    projectId: 'leap-f50f3',
    storageBucket: 'leap-f50f3.appspot.com',
    iosClientId: '31700413083-ove06ts8fkvrann8t8tiqnvjtk6br03g.apps.googleusercontent.com',
    iosBundleId: 'com.example.leap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt0fWYENz-TfXifceRsdd2e05a7Tq0kr0',
    appId: '1:31700413083:ios:fb5f52126aa8f0e7aa343e',
    messagingSenderId: '31700413083',
    projectId: 'leap-f50f3',
    storageBucket: 'leap-f50f3.appspot.com',
    iosClientId: '31700413083-ove06ts8fkvrann8t8tiqnvjtk6br03g.apps.googleusercontent.com',
    iosBundleId: 'com.example.leap',
  );
}
